server:
  port: 8080

spring:
  application:
    name: foo-service-consumer

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/